# Generated by Django 3.0.5 on 2020-04-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidestimator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='severeimpact',
            name='casesForIcuByRequestedTime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='severeimpact',
            name='casesForVentilatorsByRequestedTime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='severeimpact',
            name='currentlyInfected',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='severeimpact',
            name='hospitalBedsPerRequestedTime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='severeimpact',
            name='infectionByRequestedAtTime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='severeimpact',
            name='severeCaseByRequestedTime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
